config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /fr|en/ do
    devise_for :users
    root to: "pages#home"

    resources :pages

    resource :account, only: [:show] do
      resources :experiences, only: [:index, :create, :update, :destroy], module: :accounts
    end
  end

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :experiences
end

app/controllers/accounts/experiences_controller.rb
class Accounts::ExperiencesController < ApplicationController

  def index
    @experiences = Experience.all
    @experience  = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)

    if @experience.save
      redirect_to account_experiences_path
    else
      render 'new'
    end
  end

  def update
  end

  def destroy
  end

  private

  def experience_params
    params.require(:experience).permit(:user_id, :job_title, :job_content, :start_date, :end_date, :company_name, :company_link)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def show
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/accounts/experiences/index.slim
- content_for :title, "Gérer les expériences"

.container
  .row
    .col-xs-12
      ul.list-inline
        - @experiences.each do |experience|
          li
            p= experience.job_title
            p= experience.job_content

  .row
    .col-xs-12
      h1 Ajouter une expérience
      = simple_form_for [:account, @experience] do |f|
        = f.error_notification
        = f.input :job_title
        = f.input :job_content
        = f.input :start_date
        = f.input :end_date
        = f.input :company_name
        = f.input :company_link
        = f.submit

app/views/accounts/show.slim
h1 hello, world

= link_to 'Sign out', destroy_user_session_path, method: 'delete'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) || "Your App name" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

  <%= render 'shared/footer' %>

  <%= javascript_include_tag 'application' %>
  <%= yield(:after_js) %>
</body>
</html>

app/views/pages/_presentation.slim
.container
  .row
    .col-xs-12.col-sm-4.col-md-3
      .title.padded
        h1= t '.whoami'
    .col-xs-12.col-sm-8.col-md-9
      .title.padded
        p= t('.description').html_safe

app/views/pages/home.html.erb
<% content_for :title, 'Welcome on Sonia\'s wonderful portfolio' %>

<div id="banner" class="text-center">
  <h1><%= t('.name').html_safe %></h1>
  <div class="expandUp">
    <h3><%= t '.position' %></h3>
  </div>
  <ul class="list-inline">
    <li><a href="mailto:sonia@auboulotsimone.fr"><i class="fa fa-paper-plane"></i></a></li>
    <li><a href="https://github.com/soniaprevost"><i class="fa fa-github"></a></i></li>
    <li><a href="https://fr.linkedin.com/in/soniaprevost"><i class="fa fa-linkedin-square"></a></i></li>
    <li><a href="https://twitter.com/wondersonja"><i class="fa fa-twitter"></i></a></li>
  </ul>
</div>

<%= render 'presentation' %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 text-center private">
      <%= link_to 'Private', account_path %>
    </div>
  </div>
</div>

app/views/shared/_footer.slim
#footer
  .text-center
    p= t '.madewithlove'